### PR TITLE
Make the WASM output file smaller

### LINKED ISSUE #352: Investigate Okapi WASM binary size
### Requirements
- [x] Identify a way (cargo profiles/flags) to optimize the WASM binary size: https://doc.rust-lang.org/cargo/reference/profiles.html
- [x] Reduce the WASM binary size if possible
- [x] Trim any unnecessary dependencies in `cargo.lock`
- [x] Trim the fat on other build targets as well, if possible.(iOS is 50 MB)

### Reasoning
We need to keep the performance and download speed of okapi WASM up. It is currently (2022-02-10) around 4MB (19MB in static form). Ideally it will become a lot smaller than that.

### PR DESCRIPTION
**Pull request by fundthmcalculus**
closes #352

### CODE REVIEW

**Comment by tmarkovski** [comment]
What are the improvements in size?

This also needs to be regression tested with Blazor to ensure that the compiled wasm can still be embedded.

**Comment by fundthmcalculus** [comment]
> What are the improvements in size?

`wc -c okapi.wasm`
Release as now: 4.1 MB
Release with settings: 2.44MB
Release with `wasm-opt` enabled (currently disabled because we use `.a` not `.wasm`): 1.9 MB
> 
> This also needs to be regression tested with Blazor to ensure that the compiled wasm can still be embedded.

Best way to regression test with Blazor? Do we have a unit/integration test for blazor?

**Comment by tmarkovski** [comment]
There's no integration test, we should probably add one.
Best way to test is to build the Nuget locally using the created libraries and try invoking the library in Blazor app.
There's a sample here https://github.com/trinsic-id/okapi-examples/tree/main/dotnet/BlazorSample

**Comment by fundthmcalculus** [comment]
> There's no integration test, we should probably add one. Best way to test is to build the Nuget locally using the created libraries and try invoking the library in Blazor app. There's a sample here https://github.com/trinsic-id/okapi-examples/tree/main/dotnet/BlazorSample

Good call. Let me add one. We need to have tests for everything possible. 👍

**Comment by tmarkovski** [comment]
> Good call. Let me add one. We need to have tests for everything possible. 👍

You may need to reference okapi from a local nuget in the blazor app. If referenced as a project, the MSBuild restore targets may not be loaded correctly.
https://github.com/trinsic-id/okapi/blob/7ee00f97bcee8867962fd325f96b42eec1a69437/dotnet/Library/Okapi/Okapi.csproj#L48

**Comment by fundthmcalculus** [comment]
Upon further digging, if I optimize the wasm output file, the `.a` file gets larger. This is a false economy optimization.

**Pull request closed without merging**
