### PR TITLE
Add oberon proof size assertions

### PR DESCRIPTION
**Pull request by tmarkovski**

### CODE REVIEW

**Review by fundthmcalculus — COMMENTED** [review]
Are we forcing the full 256 bytes of proof to be sent? Some languages only send the first 64.

**Comment by tmarkovski** [comment]
> Are we forcing the full 256 bytes of proof to be sent? Some languages only send the first 64.

Which ones?

**Comment by fundthmcalculus** [comment]
> > Are we forcing the full 256 bytes of proof to be sent? Some languages only send the first 64.
> 
> Which ones?

off the top of my head, I don't remember. Some of the language-specific blake3 bindings are different. Now that we have blake3 exposed via okapi, it won't be an issue. I'll track this verification work here: https://github.com/trinsic-id/sdk/issues/456

**Comment by tmarkovski** [comment]
This is related to proof size of oberon. It wouldn't work with any other partial size. It used to be 96 bytes, now it's 256.

**Comment by fundthmcalculus** [comment]
> This is related to proof size of oberon. It wouldn't work with any other partial size. It used to be 96 bytes, now it's 256.

ah okay. I was referring to the blake3 hashed nonce in sdk. Still something to change, but less related than I thought.

**Review by sethjback — APPROVED** [review]

**Review by sethjback — APPROVED** [review]

**Comment by tmarkovski** [comment]
@fundthmcalculus This can't be merged without your approval. Mind giving it thumbs up?

**Review by fundthmcalculus — APPROVED** [review]

**Pull request merged**
